// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestCihaziUretimPlanlama.Infrastructure.Data;

#nullable disable

namespace TestCihaziUretimPlanlama.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250602131447_CompleteSystemWithRelations")]
    partial class CompleteSystemWithRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique()
                        .HasDatabaseName("IX_Departmanlar_Ad");

                    b.ToTable("Departmanlar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "PMD Test Departmanı",
                            Ad = "PMD",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6373),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "CNC İşleme Departmanı",
                            Ad = "CNC",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6385),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Test Tamir Bakım Departmanı",
                            Ad = "Teknik",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6387),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Sure")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId")
                        .HasDatabaseName("IX_Gorevler_DepartmanId");

                    b.HasIndex("DepartmanId", "Ad")
                        .IsUnique()
                        .HasDatabaseName("IX_Gorevler_DepartmanId_Ad");

                    b.ToTable("Gorevler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "PV hazırlama işlemleri",
                            Ad = "PV Hazırlama",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6481),
                            DepartmanId = 1,
                            IsDeleted = false,
                            Sure = 32
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Şematik çizim ve malzeme kontrol işlemleri",
                            Ad = "Şematik Çizme ve Eksik Malzeme Kontrolü",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6482),
                            DepartmanId = 1,
                            IsDeleted = false,
                            Sure = 32
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Test programı hazırlama işlemleri",
                            Ad = "Test Programı Hazırlama",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6484),
                            DepartmanId = 1,
                            IsDeleted = false,
                            Sure = 40
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Kablolama ve el ölçümü kontrol işlemleri",
                            Ad = "Kablolama ve test adımları tek adım modunda kontrol (El Ölçümü)",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6485),
                            DepartmanId = 1,
                            IsDeleted = false,
                            Sure = 5
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "CNC ile PCB sabitleme işlemleri",
                            Ad = "CNC Test Cihazı PCB Sabitleme",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6486),
                            DepartmanId = 2,
                            IsDeleted = false,
                            Sure = 3
                        },
                        new
                        {
                            Id = 12,
                            Aciklama = "CNC ile üst baskı işlemleri",
                            Ad = "CNC Test Cihazı Üst Baskı",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6488),
                            DepartmanId = 2,
                            IsDeleted = false,
                            Sure = 8
                        },
                        new
                        {
                            Id = 16,
                            Aciklama = "CNC manuel işleme",
                            Ad = "CNC Manuel İş",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6489),
                            DepartmanId = 2,
                            IsDeleted = false,
                            Sure = 32
                        },
                        new
                        {
                            Id = 17,
                            Aciklama = "CNC konsept adaptör işleme",
                            Ad = "CNC Konsept Adaptör İşleme",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6490),
                            DepartmanId = 2,
                            IsDeleted = false,
                            Sure = 32
                        },
                        new
                        {
                            Id = 18,
                            Aciklama = "CNC test cihazı plakası işleme",
                            Ad = "CNC Test Cihazı Plakası İşleme",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6491),
                            DepartmanId = 2,
                            IsDeleted = false,
                            Sure = 16
                        },
                        new
                        {
                            Id = 19,
                            Aciklama = "CNC test cihazı kontrol ve ayar işlemleri",
                            Ad = "CNC Test Cihazı Kontrol / Ayar",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6493),
                            DepartmanId = 2,
                            IsDeleted = false,
                            Sure = 32
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Malzeme hazırlık işlemleri",
                            Ad = "Malzeme Hazırlık",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6494),
                            DepartmanId = 3,
                            IsDeleted = false,
                            Sure = 3
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Teknik kontrol listesi işlemleri",
                            Ad = "Teknik Checklist",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6495),
                            DepartmanId = 3,
                            IsDeleted = false,
                            Sure = 8
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Test programı kontrol ve iğne yerleştirme",
                            Ad = "TP Kontrol ve İğne yerleştirme",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6496),
                            DepartmanId = 3,
                            IsDeleted = false,
                            Sure = 4
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Pertenax ve devre hazırlık işlemleri",
                            Ad = "Pertenax ve Devre Hazırlığı",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6497),
                            DepartmanId = 3,
                            IsDeleted = false,
                            Sure = 10
                        },
                        new
                        {
                            Id = 10,
                            Aciklama = "Malzeme sağlamlık test işlemleri",
                            Ad = "Malzeme Sağlamlık Testi",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6499),
                            DepartmanId = 3,
                            IsDeleted = false,
                            Sure = 2
                        },
                        new
                        {
                            Id = 11,
                            Aciklama = "Ürün etiketleme işlemleri",
                            Ad = "Etiketleme",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6500),
                            DepartmanId = 3,
                            IsDeleted = false,
                            Sure = 3
                        },
                        new
                        {
                            Id = 13,
                            Aciklama = "Test cihazı kablolama ve montaj işlemleri",
                            Ad = "Test Cihazı Kablolama ve Montaj",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6501),
                            DepartmanId = 3,
                            IsDeleted = false,
                            Sure = 24
                        },
                        new
                        {
                            Id = 14,
                            Aciklama = "Test cihazı malzeme yerleştirme işlemleri",
                            Ad = "Test Cihazı Malzeme Yerleştirme",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6502),
                            DepartmanId = 3,
                            IsDeleted = false,
                            Sure = 3
                        },
                        new
                        {
                            Id = 15,
                            Aciklama = "Şema ve test cihazı kontrol işlemleri",
                            Ad = "Şema ve Test Cihazı Kontrolü",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6503),
                            DepartmanId = 3,
                            IsDeleted = false,
                            Sure = 15
                        });
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique()
                        .HasDatabaseName("IX_Kategoriler_Ad");

                    b.ToTable("Kategoriler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "İğne plakası üretim kategorisi",
                            Ad = "İğne Plakası",
                            Aktif = true,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6525),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.KategoriGorevBagimlilik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArdilKategoriGorevSablonuId")
                        .HasColumnType("integer");

                    b.Property<int>("BagimlilikTipi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GecikmeGunu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OncuKategoriGorevSablonuId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArdilKategoriGorevSablonuId");

                    b.HasIndex("OncuKategoriGorevSablonuId", "ArdilKategoriGorevSablonuId")
                        .IsUnique()
                        .HasDatabaseName("IX_KategoriGorevBagimliliklari_Oncu_Ardil");

                    b.ToTable("KategoriGorevBagimliliklari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArdilKategoriGorevSablonuId = 2,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6605),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArdilKategoriGorevSablonuId = 3,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6606),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 2
                        },
                        new
                        {
                            Id = 3,
                            ArdilKategoriGorevSablonuId = 4,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6607),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 1
                        },
                        new
                        {
                            Id = 4,
                            ArdilKategoriGorevSablonuId = 5,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6608),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 2
                        },
                        new
                        {
                            Id = 5,
                            ArdilKategoriGorevSablonuId = 5,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6609),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 4
                        },
                        new
                        {
                            Id = 6,
                            ArdilKategoriGorevSablonuId = 6,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6610),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 5
                        },
                        new
                        {
                            Id = 7,
                            ArdilKategoriGorevSablonuId = 7,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6611),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 6
                        },
                        new
                        {
                            Id = 8,
                            ArdilKategoriGorevSablonuId = 8,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6612),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 7
                        },
                        new
                        {
                            Id = 9,
                            ArdilKategoriGorevSablonuId = 9,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6613),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 8
                        },
                        new
                        {
                            Id = 10,
                            ArdilKategoriGorevSablonuId = 10,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6614),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 9
                        },
                        new
                        {
                            Id = 11,
                            ArdilKategoriGorevSablonuId = 11,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6615),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 10
                        },
                        new
                        {
                            Id = 12,
                            ArdilKategoriGorevSablonuId = 12,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6615),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 11
                        },
                        new
                        {
                            Id = 13,
                            ArdilKategoriGorevSablonuId = 13,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6616),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 12
                        },
                        new
                        {
                            Id = 14,
                            ArdilKategoriGorevSablonuId = 14,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6617),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 13
                        },
                        new
                        {
                            Id = 15,
                            ArdilKategoriGorevSablonuId = 15,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6618),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 3
                        },
                        new
                        {
                            Id = 16,
                            ArdilKategoriGorevSablonuId = 15,
                            BagimlilikTipi = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6619),
                            GecikmeGunu = 0,
                            IsDeleted = false,
                            OncuKategoriGorevSablonuId = 14
                        });
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.KategoriGorevSablonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GorevId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<int?>("OzelSure")
                        .HasColumnType("integer");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("KategoriId", "GorevId")
                        .IsUnique()
                        .HasDatabaseName("IX_KategoriGorevSablonlari_KategoriId_GorevId");

                    b.HasIndex("KategoriId", "Sira")
                        .IsUnique()
                        .HasDatabaseName("IX_KategoriGorevSablonlari_KategoriId_Sira");

                    b.ToTable("KategoriGorevSablonlari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6541),
                            GorevId = 1,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 32,
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6543),
                            GorevId = 2,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 32,
                            Sira = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6544),
                            GorevId = 3,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 40,
                            Sira = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6546),
                            GorevId = 18,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 16,
                            Sira = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6547),
                            GorevId = 8,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 4,
                            Sira = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6548),
                            GorevId = 4,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 3,
                            Sira = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6550),
                            GorevId = 9,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 10,
                            Sira = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6577),
                            GorevId = 10,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 2,
                            Sira = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6579),
                            GorevId = 12,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 8,
                            Sira = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6580),
                            GorevId = 14,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 3,
                            Sira = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6581),
                            GorevId = 13,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 24,
                            Sira = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6582),
                            GorevId = 11,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 3,
                            Sira = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6583),
                            GorevId = 15,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 15,
                            Sira = 13
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6584),
                            GorevId = 6,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 8,
                            Sira = 14
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6585),
                            GorevId = 7,
                            IsDeleted = false,
                            KategoriId = 1,
                            OzelSure = 5,
                            Sira = 15
                        });
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("CalismaSekli")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DonerVardiyaBaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DonerVardiyaBaslangicTipi")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonelNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SabitVardiyaTipi")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId")
                        .HasDatabaseName("IX_Personeller_DepartmanId");

                    b.HasIndex("PersonelNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Personeller_PersonelNo");

                    b.ToTable("Personeller", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Kaan",
                            Aktif = true,
                            CalismaSekli = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6644),
                            DepartmanId = 1,
                            IsDeleted = false,
                            PersonelNo = "P001",
                            SabitVardiyaTipi = 1,
                            Soyad = "Karamancı"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Mert",
                            Aktif = true,
                            CalismaSekli = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6646),
                            DepartmanId = 1,
                            IsDeleted = false,
                            PersonelNo = "P002",
                            SabitVardiyaTipi = 1,
                            Soyad = "Göncü"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Kadir",
                            Aktif = true,
                            CalismaSekli = 2,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6650),
                            DepartmanId = 2,
                            DonerVardiyaBaslangicTarihi = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonerVardiyaBaslangicTipi = 3,
                            IsDeleted = false,
                            PersonelNo = "P003",
                            Soyad = "Vural"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Ramazan",
                            Aktif = true,
                            CalismaSekli = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6652),
                            DepartmanId = 2,
                            IsDeleted = false,
                            PersonelNo = "P004",
                            SabitVardiyaTipi = 2,
                            Soyad = "Öztürk"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Adem",
                            Aktif = true,
                            CalismaSekli = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6654),
                            DepartmanId = 2,
                            IsDeleted = false,
                            PersonelNo = "P005",
                            SabitVardiyaTipi = 2,
                            Soyad = "Yüksel"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Sinan",
                            Aktif = true,
                            CalismaSekli = 2,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6655),
                            DepartmanId = 3,
                            DonerVardiyaBaslangicTarihi = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonerVardiyaBaslangicTipi = 3,
                            IsDeleted = false,
                            PersonelNo = "P006",
                            Soyad = "Tekyol"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Emre",
                            Aktif = true,
                            CalismaSekli = 2,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6658),
                            DepartmanId = 3,
                            DonerVardiyaBaslangicTarihi = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonerVardiyaBaslangicTipi = 4,
                            IsDeleted = false,
                            PersonelNo = "P007",
                            Soyad = "Kahveci"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Nuri",
                            Aktif = true,
                            CalismaSekli = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6659),
                            DepartmanId = 3,
                            IsDeleted = false,
                            PersonelNo = "P008",
                            SabitVardiyaTipi = 1,
                            Soyad = "Ersipahi"
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Mustafa",
                            Aktif = true,
                            CalismaSekli = 2,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6661),
                            DepartmanId = 1,
                            DonerVardiyaBaslangicTarihi = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonerVardiyaBaslangicTipi = 3,
                            IsDeleted = false,
                            PersonelNo = "P009",
                            Soyad = "Durgun"
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Mehmet Ali",
                            Aktif = true,
                            CalismaSekli = 2,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6662),
                            DepartmanId = 1,
                            DonerVardiyaBaslangicTarihi = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonerVardiyaBaslangicTipi = 4,
                            IsDeleted = false,
                            PersonelNo = "P010",
                            Soyad = "Binici"
                        },
                        new
                        {
                            Id = 11,
                            Ad = "İbrahim",
                            Aktif = true,
                            CalismaSekli = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6664),
                            DepartmanId = 3,
                            IsDeleted = false,
                            PersonelNo = "P011",
                            SabitVardiyaTipi = 1,
                            Soyad = "Gelen"
                        });
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.PersonelGorevYetkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GorevId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("PersonelId", "GorevId")
                        .IsUnique()
                        .HasDatabaseName("IX_PersonelGorevYetkinlikleri_PersonelId_GorevId");

                    b.ToTable("PersonelGorevYetkinlikleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6673),
                            GorevId = 1,
                            IsDeleted = false,
                            PersonelId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6674),
                            GorevId = 2,
                            IsDeleted = false,
                            PersonelId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6675),
                            GorevId = 3,
                            IsDeleted = false,
                            PersonelId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6676),
                            GorevId = 7,
                            IsDeleted = false,
                            PersonelId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6680),
                            GorevId = 1,
                            IsDeleted = false,
                            PersonelId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6681),
                            GorevId = 2,
                            IsDeleted = false,
                            PersonelId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6682),
                            GorevId = 3,
                            IsDeleted = false,
                            PersonelId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6682),
                            GorevId = 7,
                            IsDeleted = false,
                            PersonelId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6684),
                            GorevId = 5,
                            IsDeleted = false,
                            PersonelId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6685),
                            GorevId = 12,
                            IsDeleted = false,
                            PersonelId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6686),
                            GorevId = 16,
                            IsDeleted = false,
                            PersonelId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6713),
                            GorevId = 17,
                            IsDeleted = false,
                            PersonelId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6714),
                            GorevId = 18,
                            IsDeleted = false,
                            PersonelId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6714),
                            GorevId = 19,
                            IsDeleted = false,
                            PersonelId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6717),
                            GorevId = 5,
                            IsDeleted = false,
                            PersonelId = 4
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6718),
                            GorevId = 5,
                            IsDeleted = false,
                            PersonelId = 5
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6719),
                            GorevId = 4,
                            IsDeleted = false,
                            PersonelId = 6
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6720),
                            GorevId = 8,
                            IsDeleted = false,
                            PersonelId = 6
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6720),
                            GorevId = 9,
                            IsDeleted = false,
                            PersonelId = 6
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6721),
                            GorevId = 10,
                            IsDeleted = false,
                            PersonelId = 6
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6722),
                            GorevId = 11,
                            IsDeleted = false,
                            PersonelId = 6
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6723),
                            GorevId = 13,
                            IsDeleted = false,
                            PersonelId = 6
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6724),
                            GorevId = 14,
                            IsDeleted = false,
                            PersonelId = 6
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6725),
                            GorevId = 15,
                            IsDeleted = false,
                            PersonelId = 6
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6727),
                            GorevId = 4,
                            IsDeleted = false,
                            PersonelId = 7
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6727),
                            GorevId = 8,
                            IsDeleted = false,
                            PersonelId = 7
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6728),
                            GorevId = 9,
                            IsDeleted = false,
                            PersonelId = 7
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6729),
                            GorevId = 10,
                            IsDeleted = false,
                            PersonelId = 7
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6730),
                            GorevId = 11,
                            IsDeleted = false,
                            PersonelId = 7
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6731),
                            GorevId = 13,
                            IsDeleted = false,
                            PersonelId = 7
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6732),
                            GorevId = 14,
                            IsDeleted = false,
                            PersonelId = 7
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6733),
                            GorevId = 15,
                            IsDeleted = false,
                            PersonelId = 7
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6735),
                            GorevId = 6,
                            IsDeleted = false,
                            PersonelId = 8
                        });
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.PersonelIzin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId")
                        .HasDatabaseName("IX_PersonelIzinleri_PersonelId");

                    b.HasIndex("BaslangicTarihi", "BitisTarihi")
                        .HasDatabaseName("IX_PersonelIzinleri_Tarih");

                    b.ToTable("PersonelIzinleri", (string)null);
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.PlanDisiTarih", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("TekrarliMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Tarih")
                        .HasDatabaseName("IX_PlanDisiTarihler_Tarih");

                    b.ToTable("PlanDisiTarihler", (string)null);
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IstenilenBaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<bool>("KategoriSablonuKullan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Musteri")
                        .HasColumnType("integer");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Oncelik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<DateTime?>("SonTeslimTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UretimNumarasi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Durum")
                        .HasDatabaseName("IX_Siparisler_Durum");

                    b.HasIndex("IstenilenBaslangicTarihi")
                        .HasDatabaseName("IX_Siparisler_IstenilenBaslangicTarihi");

                    b.HasIndex("KategoriId");

                    b.HasIndex("UretimNumarasi")
                        .IsUnique()
                        .HasDatabaseName("IX_Siparisler_UretimNumarasi");

                    b.ToTable("Siparisler", (string)null);
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.UretimGorevBagimlilik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArdilUretimGoreviId")
                        .HasColumnType("integer");

                    b.Property<int>("BagimlilikTipi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GecikmeGunu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OncuUretimGoreviId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArdilUretimGoreviId");

                    b.HasIndex("OncuUretimGoreviId", "ArdilUretimGoreviId")
                        .IsUnique()
                        .HasDatabaseName("IX_UretimGorevBagimliliklari_Oncu_Ardil");

                    b.ToTable("UretimGorevBagimliliklari", (string)null);
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.UretimGorevi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtananPersonelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GercekBaslangic")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("GercekBitis")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GorevId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("PlanlananBaslangic")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PlanlananBitis")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SiparisId")
                        .HasColumnType("integer");

                    b.Property<int>("Sure")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AtananPersonelId")
                        .HasDatabaseName("IX_UretimGorevleri_AtananPersonelId");

                    b.HasIndex("Durum")
                        .HasDatabaseName("IX_UretimGorevleri_Durum");

                    b.HasIndex("GorevId");

                    b.HasIndex("PlanlananBaslangic")
                        .HasDatabaseName("IX_UretimGorevleri_PlanlananBaslangic");

                    b.HasIndex("SiparisId")
                        .HasDatabaseName("IX_UretimGorevleri_SiparisId");

                    b.ToTable("UretimGorevleri", (string)null);
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.VardiyaTanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("CumartesiCalismasi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VardiyaTipi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VardiyaTipi")
                        .IsUnique()
                        .HasDatabaseName("IX_VardiyaTanimlari_VardiyaTipi");

                    b.ToTable("VardiyaTanimlari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6461),
                            CumartesiCalismasi = false,
                            IsDeleted = false,
                            VardiyaTipi = 1
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            BaslangicSaati = new TimeSpan(0, 7, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 15, 0, 0, 0),
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6463),
                            CumartesiCalismasi = true,
                            IsDeleted = false,
                            VardiyaTipi = 2
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            BaslangicSaati = new TimeSpan(0, 7, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 15, 0, 0, 0),
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6464),
                            CumartesiCalismasi = true,
                            IsDeleted = false,
                            VardiyaTipi = 3
                        },
                        new
                        {
                            Id = 4,
                            Aktif = true,
                            BaslangicSaati = new TimeSpan(0, 15, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 23, 0, 0, 0),
                            CreatedDate = new DateTime(2025, 6, 2, 13, 14, 47, 725, DateTimeKind.Utc).AddTicks(6465),
                            CumartesiCalismasi = false,
                            IsDeleted = false,
                            VardiyaTipi = 4
                        });
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Gorev", b =>
                {
                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Departman", "Departman")
                        .WithMany("Gorevler")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.KategoriGorevBagimlilik", b =>
                {
                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.KategoriGorevSablonu", "ArdilGorev")
                        .WithMany("OncuBagimliliklar")
                        .HasForeignKey("ArdilKategoriGorevSablonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.KategoriGorevSablonu", "OncuGorev")
                        .WithMany("ArdilBagimliliklar")
                        .HasForeignKey("OncuKategoriGorevSablonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArdilGorev");

                    b.Navigation("OncuGorev");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.KategoriGorevSablonu", b =>
                {
                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Gorev", "Gorev")
                        .WithMany("KategoriSablonlari")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Kategori", "Kategori")
                        .WithMany("GorevSablonlari")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Personel", b =>
                {
                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Departman", "Departman")
                        .WithMany("Personeller")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.PersonelGorevYetkinlik", b =>
                {
                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Gorev", "Gorev")
                        .WithMany("PersonelYetkinlikleri")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Personel", "Personel")
                        .WithMany("GorevYetkinlikleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.PersonelIzin", b =>
                {
                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Personel", "Personel")
                        .WithMany("Izinler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Siparis", b =>
                {
                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Kategori", "Kategori")
                        .WithMany("Siparisler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.UretimGorevBagimlilik", b =>
                {
                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.UretimGorevi", "ArdilGorev")
                        .WithMany("OncuBagimliliklar")
                        .HasForeignKey("ArdilUretimGoreviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.UretimGorevi", "OncuGorev")
                        .WithMany("ArdilBagimliliklar")
                        .HasForeignKey("OncuUretimGoreviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArdilGorev");

                    b.Navigation("OncuGorev");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.UretimGorevi", b =>
                {
                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Personel", "AtananPersonel")
                        .WithMany("AtanmisGorevler")
                        .HasForeignKey("AtananPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Gorev", "Gorev")
                        .WithMany("UretimGorevleri")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestCihaziUretimPlanlama.Core.Entities.Siparis", "Siparis")
                        .WithMany("UretimGorevleri")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtananPersonel");

                    b.Navigation("Gorev");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Departman", b =>
                {
                    b.Navigation("Gorevler");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Gorev", b =>
                {
                    b.Navigation("KategoriSablonlari");

                    b.Navigation("PersonelYetkinlikleri");

                    b.Navigation("UretimGorevleri");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Kategori", b =>
                {
                    b.Navigation("GorevSablonlari");

                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.KategoriGorevSablonu", b =>
                {
                    b.Navigation("ArdilBagimliliklar");

                    b.Navigation("OncuBagimliliklar");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Personel", b =>
                {
                    b.Navigation("AtanmisGorevler");

                    b.Navigation("GorevYetkinlikleri");

                    b.Navigation("Izinler");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.Siparis", b =>
                {
                    b.Navigation("UretimGorevleri");
                });

            modelBuilder.Entity("TestCihaziUretimPlanlama.Core.Entities.UretimGorevi", b =>
                {
                    b.Navigation("ArdilBagimliliklar");

                    b.Navigation("OncuBagimliliklar");
                });
#pragma warning restore 612, 618
        }
    }
}
